twig:
    file_name_pattern: '*.twig'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - "@TalesFromADevFlowbite/form/default.html.twig"

when@test:
    twig:
        strict_variables: true
